### ISSUE TITLE
Error Unexpected token with Browserify

### ISSUE THREAD

**Issue by nghiepdev** [hilongjw/vue-datepicker#1]
Hi, 
I use vuejs ^1.0.16.
My error:
Link capture image: http://i.imgur.com/ffKGi0U.jpg
![Error](http://i.imgur.com/ffKGi0U.jpg)

**Comment by hilongjw** [comment]
Hi,I have not tested with  Browserify,  but I will test it.

**Comment by hilongjw** [comment]
I have added es5 in datepicker component

**Comment by Helfull** [comment]
how long until you tag it for npm?

i am on vue-datepicker 1.1.0

and getting the same error

**Comment by talionarold** [comment]
Browserify just does not know that is .vue file, so it's just do not parse it with vueify. You can add such vue components directly with node_modules/vue-datepicker/vue-datepicker.vue and then Browserify will know that is .vue file and will parse it correctly.

But it's only quick workaround, and it must be fixed through changing package.json "main" section

**Comment by hilongjw** [comment]
@Talionar  Thanks

**Comment by EmilMoe** [comment]
Why is this closed? It still doesn't work
