### ISSUE TITLE
Inconsisent margin between week row and day row when switching months

### ISSUE THREAD

**Issue by jiangfengming** [hilongjw/vue-datepicker#2]
![image](https://cloud.githubusercontent.com/assets/11750532/13032944/bf99e71e-d340-11e5-8bf0-de06ceaa68dd.png)

![image](https://cloud.githubusercontent.com/assets/11750532/13032942/b125840e-d340-11e5-8dd8-46eebf939bb6.png)

The problem is caused by vertical alignment of the empty `.day` cells. After adding `vertical-align: middle` to `.day`, the margin becomes the same, but too narrow. Adding `margin-bottom` to `.week` looks better.

**Comment by hilongjw** [comment]
thanks
