### ISSUE TITLE
Question: Did vue-datepicker accepte range/multi-selection?

### ISSUE THREAD

**Issue by YanshuoH** [hilongjw/vue-datepicker#20]
Hello there,

Could you please tell me if this datepicker allow range/multi-selection? Or I'm just too dumb to find out the API? :disappointed: 

Thanks.

H.

**Comment by hilongjw** [comment]
Hi, that's necessary featrue, it is not yet supported, I'll add later

**Comment by YanshuoH** [comment]
Thanks for response.

**Comment by hilongjw** [comment]
Hi, I just did it

**Comment by YanshuoH** [comment]
Duly noted! Many thanks
