### ISSUE TITLE
引入该插件后项目体积剧增

### ISSUE THREAD

**Issue by facesea** [hilongjw/vue-datepicker#21]
我的项目本来js文件打包后只有2MB多，引入本插件后就变成4.5MB了，在node_module文件里查看，发现项目本身不大，但是引入的lodash库文件却大的吓人：2MB，我去lodash官方看了，其实下载lodash也就22kb，但不知为何到了npm中就变得如此巨大了，望优化一下，非常喜欢这个插件。

**Comment by hilongjw** [comment]
我去掉了lodash的依赖，现在只依赖moment，应该会不是很大

**Comment by facesea** [comment]
更新版本后体积确实小了1MB多，谢谢~~望越做越好
