### ISSUE TITLE
设置limit Bug

### ISSUE THREAD

**Issue by facesea** [hilongjw/vue-datepicker#22]
配置如下：

```
limit: [{
  type: 'weekday',
  available: [1, 2, 3, 4, 5]
}, {
  type: 'fromto',
  from: '2016-05-15'
}]
```

我默认不填`to`就是允许`>= from`的时间，有以下问题：
- 只能选择2016-05-15之后一周的时间

将`to`设置为`2017-05-15`后，只有当月是正确的，其他月份比如4月、6月的日期可点

**Comment by hilongjw** [comment]
我明白你说的这个问题了，我马上会修复它

**Comment by wavelynn** [comment]
limit的bug 不仅仅是这个哦 

http://hilongjw.github.io/vue-datepicker/demo.html#!/
错位比较严重 而且不准确 

```
.isBetween(limit.from, limit.to)) => 没有对输入的值格式化 
```

**Comment by wavelynn** [comment]
```
// false
moment('2010-10-2').isBetween('2010-10-01', '2010-10-25') 
```

问题原因： 上面返回的是false 判断错误

**Comment by hilongjw** [comment]
@wavelynn 嗯，没有对那里的参数做验证

`
2010-10-2  
2010-10-02 
`
嗯，是发现了这个问题

**Comment by movostudios** [comment]
Hi. Sorry, I am a non-Chinese speaker. I'm not sure if this is the same issue:

If I limit the weekday like:
~~~
{
      type: 'weekday',
      available: [1, 2, 3, 4, 5]
}
~~~

I get the correct result for the current month only.
![screen shot 2016-08-05 at 12 19 26](https://cloud.githubusercontent.com/assets/2419418/17435231/5488df26-5b07-11e6-80dd-8a589ea705d8.png)

Notice that this month is un selectable. In this example, we can see the start of September. This IS selectable and it shouldn't be.

I hope that make sense. If this is a different issue, let me know and I will move this to another issue.

Cheers - Love the datepicker - Thank you!!

**Comment by hilongjw** [comment]
fixed
