### ISSUE TITLE
About hours and minute

### ISSUE THREAD

**Issue by smartpierre** [hilongjw/vue-datepicker#3]
Hi, I just downloaded the component and it works great, however I have some things to say : 

The minutes should be between 00 and 59 instead of being between 01 and 60 :It cause to have an invalid date with moment if you set the minutes to 60

I would also suggest strongly to do the same for the hours : hours are from 00 to 23, so it doesn't cause confusion and we are getting closer to ISO 8601 https://en.wikipedia.org/wiki/ISO_8601

Thanks !

**Comment by smartpierre** [comment]
Also, on an Invalid date, the whole component crash and is unusable

![screenshot from 2016-02-23 18-11-51](https://cloud.githubusercontent.com/assets/8858750/13259736/f46b7db2-da58-11e5-879b-ce6aecef3ee7.png)

**Comment by hilongjw** [comment]
Hi, got it, I will fix them as soon as possible

**Comment by smartpierre** [comment]
:+1:

**Comment by hilongjw** [comment]
I've fixed it ,thanks
