### ISSUE TITLE
Remove the default style

### ISSUE THREAD

**Issue by Sopamo** [hilongjw/vue-datepicker#33]
I don't think you should have default styles for the input element in the component. It's great that we are able to override the styles with the component config (and you already have the styles in the documentation). But when I'm using the component with any other library the date fields will look different  which is definitely not what I want.

If you want, I can create a pull request.

**Comment by hilongjw** [comment]
Hi, @Sopamo thanks. welcome for your pull request.

**Comment by exoticknight** [comment]
正打算问作者怎么办，就搜到这个了

**Comment by Sopamo** [comment]
I'm not quite sure what you wrote, but I already submitted the pull request :)

**Comment by exoticknight** [comment]
@Sopamo 
oh I just express my concern about it cause I meet the deadline in two days
thx for you pull request ^_^

**Comment by Sopamo** [comment]
Oh okay :) I hope it gets merged soon @hilongjw

**Comment by hilongjw** [comment]
sorry, I'll do that right now
