### ISSUE TITLE
Limit weekday, following month is selectable

### ISSUE THREAD

**Issue by t2thec** [hilongjw/vue-datepicker#44]
Hi. Thank you for the great date picker!

Sorry, I am a non-Chinese speaker. There is an issue with the limit on weekdays where you see the following month.

If I limit the weekday like:

```
{
      type: 'weekday',
      available: [1, 2, 3, 4, 5]
}
```

I get the correct result for the current month only.

![screen shot 2016-08-05 at 12 19 26](https://cloud.githubusercontent.com/assets/2419418/17435364/31ded150-5b08-11e6-8985-44672caeac61.png)

Notice that this month is un selectable. In this example, we can see the start of September. This IS selectable and it shouldn't be.

I hope that make sense. If this is a different issue, let me know and I will move this to another issue.

Cheers - Love the datepicker - Thank you!!

**Comment by hilongjw** [comment]
Hi, thanks for your issue, I fixed it just now.

**Comment by angganegara** [comment]
Hello @hilongjw, I'm having exactly the same issue as @t2thec 
I'm using Vue 2. it's working fine on the same month, but for the next month, you can choose the disabled dates. Can you please help?

thanks

**Comment by KaliCharanV** [comment]
+1
