### ISSUE TITLE
Customize 'class' of input 

### ISSUE THREAD

**Issue by mqli** [hilongjw/vue-datepicker#45]
Nice Component.

While I being try to customize the style of the default `<input/>`, using 'inputStyle' seem a little bit complicated.

A prop of setting 'class' of the `<input/>` will be very handy for customize .

Will you accept a PR of it?

**Comment by fernandoherlo** [comment]
https://github.com/fernandoherlo/vue-datepicker/commit/c3ae387a8d8624d956d27518442181579b76cfed

**Comment by hilongjw** [comment]
thx for @elijan 's pr
