### ISSUE TITLE
throw error: this.selectedDays.$remove is not a function

### ISSUE THREAD

**Issue by bigzhu** [hilongjw/vue-datepicker#70]
Used with Vue 2.0, when multi-day select one day and unselect it

throw erro : `this.selectedDays.$remove is not a function` in vue-datepicker.vue at 
```
 if (obj.checked === true) {
          obj.checked = false;
          this.selectedDays.$remove(ctime);
        }
```

I think because in Vue 2.0  The $remove() method has been deleted

I do't know why the demo is work fine.

finally I modify the code to
```
        if (obj.checked === true) {
          obj.checked = false;
          // this.selectedDays.$remove(ctime);
          this.selectedDays.splice(this.selectedDays.indexOf(ctime), 1)
        }
```
it work fine

**Comment by hilongjw** [comment]
@bigzhu, Because I added $remove method with Array.prototype in my project.

**Comment by waratah** [comment]
$remove is deprecated in Vue2. they recommend using splice.
