### ISSUE TITLE
How to catch "change" event from a parent component?

### ISSUE THREAD

**Issue by rcubitto** [hilongjw/vue-datepicker#84]
Vue version: 1.0.28

If I'm using it as a child component, how can I grab the chosen date? I did 

```vue
<date-picker v-on:change="setFromDueDate($event)" :time.sync="''" :option="datepicker.option"></date-picker>
```

But if I log the event, it appears as `undefined`.

```vue
methods: {
    setFromDueDate: function (event) {
        console.log(event);
    }
}
```

I see that inside the component it's using `$emit` to trigger events, but shouldn't it be using `$dispatch` instead, so that the parent can grab the event?

**Comment by BojDom** [comment]
$dispatch is for vuex, the app logic is on your own choice.
Parent component can grab the $emit event also from your child date-picker component

**Comment by rcubitto** [comment]
@BojDom you are right, thanks for the clarification.
