### ISSUE TITLE
Support for days of previous/next month

### ISSUE THREAD

**Issue by veksen** [hilongjw/vue-datepicker#9]
It would be nice to support the remaining days of a week with the last and first days of the next and previous month. I looked at the source, and I'm not sure how I would implement it.

**Comment by blogui91** [comment]
@veksen , This is a good idea, i actually was working on it, i will upload my changes, meanwhile you can check it in https://github.com/blogui91/vue-datepicker if you like it , i will make PR to here :)

**Comment by hilongjw** [comment]
thx to @blogui91
