### ISSUE TITLE
Missing required prop: date

### ISSUE THREAD

**Issue by desprit** [hilongjw/vue-datepicker#93]
I'm using following versions:

```
"vue": "^1.0.0",
"vue-datepicker": "^1.3.0"
```

Datepicker component is defined according to docs:
```
<date-picker class="date-picker"   
             :time="inDate"        
             :option="option"      
             :limit="limit">       
</date-picker>                     

```
I'm getting this: `Missing required prop: date (found in component: <date-picker>)`
If I add `:date="{time: inDate}"`, it works fine. But non of my watch event works. I tried watching both `date` and `time` props. I can see date changed in datepicker. How do I catch it?

Update:
Was able to catch event listening to `'date.time'()`.

**Comment by lirugo** [comment]
find solution?
