### ISSUE TITLE
Getting exports not defined error

### ISSUE THREAD

**Issue by pwnz22** [hilongjw/vue-datepicker#97]
**Uncaught ReferenceError: exports is not defined**

![Alt](https://i.gyazo.com/2f5b1406e5a914c4a6890ebe86c8f729.png "exports is not defined")

Getting this strange error.

**Comment by praponc** [comment]
Got the same problem here

**Comment by mihaibogdan10** [comment]
+1

**Comment by ghost** [comment]
Getting it as well. Using webpack and electron if that matters.

**Comment by tigonetwork** [comment]
+1

**Comment by Shugar** [comment]
+1

**Comment by greenxiii** [comment]
+1

**Comment by greenxiii** [comment]
import myDatepicker from 'vue-datepicker/vue-datepicker-es6.vue';
That helped me

**Comment by xunyagai** [comment]
我也是引用这句话解决这个问题的“import myDatepicker from 'vue-datepicker/vue-datepicker-es6.vue'”
